spring:
  datasource:
    url: jdbc:mysql://localhost:3306/james?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.xml